package com.dxc.util;

public class Constants {

		public static final String query1 = "Select POLICYNUMBER from CLAIMS.CLAIMPOLICY where REPORTING_STATUS=";
		public static final String ClaimPolicyAggregateQuery = "SELECT DISTINCT CLMPOL.POLICYNUMBER AS policyNumber,CLM.CLAIMNUMBER AS claimNumber,PROCSITES.DESCR AS processingSite, CLM.CLAIMCAUSE AS claimCause,"
				+ " PARTY.CLIENT_ID," + " 	CLMPOL.CLAIMPOLICYID," + " PARTY.CLIENT_TYPE_ID,"
				+ " PARTY.SEARCH_COMPANY_NAME," + " PARTY.SEARCH_LAST_NAME," + " CLMPOL.CONTESTABLE AS PolFlagCONTESTABLE,"
				+ " CLMPOL.COMPROMISED AS PolFlagCOMPROMISED," + " CLMPOL.UNDERLEGALREVIEW AS PolFlagUNDERLEGALREVIEW,"
				+ " CLMPOL.PAIDTOINTERPLEADER AS PolFlagPAIDTOINTERPLEADER,"
				+ " CLMPOL.COMMONDISASTERCLAUSE AS PolFlagCOMMONDISASTERCLAUSE,"
				+ " CLMPOL.BPO_UNDERINVESTIGATION AS PolFlagBPO_UNDERINVESTIGATION,"
				+ " CLMPOL.BPO_CLAIMDEFERRED AS PolFlagBPO_CLAIMDEFERRED,"
				+ " CLMPOL.BPO_VIATICALCLAIM AS PolFlagBPO_VIATICALCLAIM,"
				+ " CLMPOL.BPO_CLIENTREVIEWREQUIRED AS PolFlagBPO_CLIENTREVIEWREQUIRED,"
				+ " CLM.CONTESTABLE AS ClmFlagCONTESTABLE," + " CLM.COMPROMISED AS ClmFlagCOMPROMISED,"
				+ " CLM.UNDERLEGALREVIEW AS ClmFlagUNDERLEGALREVIEW,"
				+ " CLM.PAIDTOINTERPLEADER AS ClmFlagPAIDTOINTERPLEADER,"
				+ " CLM.COMMONDISASTERCLAUSE AS ClmFlagCOMMONDISASTERCLAUSE,"
				+ " CLM.BPO_UNDERINVESTIGATION AS ClmFlagBPO_UNDERINVESTIGATION,"
				+ " CLM.BPO_CLAIMDEFERRED AS ClmFlagBPO_CLAIMDEFERRED,"
				+ " CLM.BPO_VIATICALCLAIM AS ClmFlagBPO_VIATICALCLAIM,"
				+ " CLM.BPO_CLIENTREVIEWREQUIRED AS ClmFlagBPO_CLIENTREVIEWREQUIRED,CLMPOL.DATE_REPORTED AS datePolicyReported,"
				+ " REGION.DESCR AS region, LEFT (COMPCODE.DESCR,3) AS company,PARTY.SEARCH_FIRST_NAME AS insFirst,PARTY.BPO_SEARCH_MIDDLE_NAME AS insMiddle,"
				+ "CLMTYP.DESCR AS claimType,INSIND.DESCR AS insInd,GRPIND.DESCR AS majorLob,"
				+ "CASE CLMPOL.PAY_ADJ_INDICATOR WHEN 0 THEN 'Unknown' WHEN 1 THEN 'Yes' WHEN 2 THEN 'No' END payAdj,"
				+ "CLMCTG.DESCR AS splHandleCode,MANLOSS.DESCR AS manner,COFDEATH.DESCR AS causeOfDeath,CLM.NOTIFYRCPTDATE AS notifiedDate,"
				+ "CLMPOL.POLICY_DATE_ENTERED AS datePolicyEntered,CLMPOL.ISSUEDATE AS issueDate,STATE.DESCR AS issueState,CLM.CLAIM_CLOSE_DATE AS closedDate,"
				+ "CLMMGMSTS.DESCR AS claimStatus,CLM.EXAMINER AS examiner,CLM.OCCURRENCEDATE AS dateOfLoss,CLMPOL.CYBERPAIDDATE AS cyberPaidDate,"
				+ "POLRPTSTS.DESCR AS polRptngStatus,POLSTS.DESCR AS policyStatus,POLCOVCLMSTS.DESCR AS policyManagementStatus,"
				+ "POLPRDCDE.DESCR AS productType,RPTPRDTYP.DESCR AS reportingProductType,	PRDSUBTYP.DESCR AS productSubtype,"
				+ "CLMCOV.PLANCODE AS planCode,PARTTYPE.DESCR AS parType,CLMCOV.CVRG_ISSUE_AGE AS issueAge,"
				+ "BEGIND.DESCR AS beagleInd,CLMCOV.BENEFITAMOUNT AS csaFaceAmt,CLMPOL.BULK_CODE AS bulkCode,"
				+ "POLAM.GROSS AS polGrossAmt, POLAM.NET AS polNetAmt, POLAM.REM AS polRemBal,"
				+ "(SELECT GEN.DESCR FROM AV.GENDERTYPE GEN , CLIENT.PERSON_DETAIL PER WHERE GEN.INTERNAL_VALUE = PER.GENDER_ID AND PER.CLIENT_ID=PARTY.CLIENT_ID) AS insuredGender,"
				+ "(SELECT RES_ST.DESCR FROM AV.STATE RES_ST,CLIENT.CLIENT_ADDRESS CADD, CLIENT.ADDRESS AD WHERE RES_ST.INTERNAL_VALUE=AD.STATE "
				+ "AND CADD.ADDRESS_ID = AD.ADDRESS_ID "
				+ "AND AD.ADDRESS_TYPE_ID IN (1,0,910,916,918) AND  CADD.CLIENT_ID=PARTY.CLIENT_ID "
				+ "ORDER BY AD.UPDATED_WHEN DESC FETCH FIRST 1 ROW ONLY) AS insResSt,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) AS cmADC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE "
				+ " CLMAMTITM.TYPE IN (11,12,64,65,66,84) "
				+ " AND CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.LEVEL IN (1,2) AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) AS cmADC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE "
				+ " CLMAMTITM.TYPE IN (11,12,64,65,66,84) "
				+ " AND CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.LEVEL IN (1,2) AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS cmAFaceAmt,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) AS ADBDC0 FROM " + " CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " WHERE  CLMAMTITM.TYPE=84 AND CLMAMTITM.LEVEL IN (1,2) "
				+ " AND CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT  COALESCE(SUM(CLMAMTITM.AMOUNT),0) AS ADBDC0 FROM "
				+ " CLAIMS.CLAIMAMOUNTITEM CLMAMTITM " + " WHERE  CLMAMTITM.TYPE=84 AND CLMAMTITM.LEVEL IN (1,2) "
				+ " AND CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS adbBenAmt, "
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " WHERE CLMAMTITM.LEVEL IN (1,2) AND CLMAMTITM.DEBITCREDIT=0 "
				+ " AND TYPE=12 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM"
				+ " WHERE CLMAMTITM.LEVEL IN (1,2) AND CLMAMTITM.DEBITCREDIT=1 AND TYPE=12"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS puaAmt,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID" + " WHERE"
				+ " CLMAMTITM.TYPE IN (11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 "
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID" + " WHERE"
				+ " CLMAMTITM.TYPE IN (11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS polFaceAmountPaid, "
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND" + " CLMAMTITM.TYPE=84 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND" + " CLMAMTITM.TYPE=84 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS polAdbAmountPaid,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND" + " CLMAMTITM.TYPE=12 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND" + " CLMAMTITM.TYPE=12 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS puaAmountPaid, "
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND"
				+ " CLMAMTITM.TYPE IN (2, 4, 14) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND"
				+ " CLMAMTITM.TYPE IN (2, 4, 14) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS premAdjustPaid, "
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND"
				+ " CLMAMTITM.TYPE IN (13,26) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND"
				+ " CLMAMTITM.TYPE IN (13,26) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS dividendsPaid,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND"
				+ " CLMAMTITM.TYPE IN (15,86) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND"
				+ " CLMAMTITM.TYPE IN (15,86) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6"
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS loanWithheld,"
				+ " (SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=0 AND" + " CLMAMTITM.TYPE = 87 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 "
				+ " AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)-(SELECT 	COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM "
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID"
				+ " WHERE CLMAMTITM.DEBITCREDIT=1 AND"
				+ " CLMAMTITM.TYPE = 87 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)+(SELECT COALESCE(SUM(CLMINTITM.AMOUNT),0) FROM CLAIMS.INTERESTPROCEEDSITEM CLMINTITM"
				+ " INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMINTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID"
				+ " WHERE CLMCOV.CLAIMID = CLMINTITM.CLAIMID "
				+ " AND STTLMNT.STATUS=6 AND CLMINTITM.IOPSTATUSCODE=0 AND CLMINTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) AS interestPaid"
				+ " FROM CLAIMS.CLAIM CLM " + " INNER JOIN  CLAIMS.CLAIMPOLICY CLMPOL "
				+ "  ON CLMPOL.CLAIMID = CLM.CLAIMID " + "INNER JOIN POLICY.LIFEPOLICY LPOL "
				+ " ON CLMPOL.HOSTCONTRACTID = LPOL.HOSTCONTRACTID " + "   INNER JOIN CLAIMS.CLAIMCOVERAGE CLMCOV "
				+ "   ON CLMCOV.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID " + "  LEFT OUTER JOIN CLIENT.PARTY PARTY "
				+ "    ON CLM.INSUREDID = PARTY.CLIENT_ID " + "    LEFT OUTER JOIN AV.CAUSEOFDEATH COFDEATH "
				+ "         ON CLM.CLAIMCAUSE=COFDEATH.INTERNAL_VALUE " + "LEFT OUTER JOIN AV.REGION REGION"
				+ "    ON LPOL.BPO_REGIONID=REGION.INTERNAL_VALUE" + " LEFT OUTER JOIN AV.PARTICIPATIONTYPE PARTTYPE "
				+ "     ON CLMCOV.PARTICIPATION_CODE_ID=PARTTYPE.INTERNAL_VALUE" + "  LEFT OUTER JOIN AV.STATE STATE"
				+ "     ON CLMPOL.ISSUESTATE=STATE.INTERNAL_VALUE" + "  LEFT OUTER JOIN AV.POLICYSTATUS POLSTS "
				+ "   ON CLMPOL.POLICYSTATUS=POLSTS.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.POLICYREPORTINGSTATUS POLRPTSTS "
				+ "     ON CLMPOL.REPORTING_STATUS=POLRPTSTS.INTERNAL_VALUE "
				+ "  LEFT OUTER JOIN AV.POLICYPRODUCTCODE POLPRDCDE" + "   ON CLMPOL.PRODUCTCODE= POLPRDCDE.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.POLICYCOVERAGECLAIMSTATUS  POLCOVCLMSTS"
				+ "             ON CLMPOL.POLCVRGCLAIMSTATUS=POLCOVCLMSTS.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.PROCESSINGSITES PROCSITES"
				+ "              ON CLMPOL.POLICY_SITE=PROCSITES.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.MANNEROFLOSS MANLOSS "
				+ "               ON CLM.MANNEROFOCCURRENCE=MANLOSS.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.CLAIMMANAGEMENTSTATUS CLMMGMSTS"
				+ "              ON CLM.CLAIMMGMTSTATUS=CLMMGMSTS.INTERNAL_VALUE"
				+ "   LEFT OUTER JOIN AV.COMPANYCODE COMPCODE"
				+ "                ON LPOL.CARRIERCODE=CAST(COMPCODE.INTERNAL_VALUE AS CHAR(10))"
				+ " LEFT OUTER JOIN AV.BEAGLEIND BEGIND "
				+ "            ON CLMPOL.BEAGLE_IND = CAST(BEGIND.INTERNAL_VALUE AS CHAR(10))"
				+ "   LEFT OUTER JOIN AV.CLAIMCATEGORY CLMCTG" + "               ON CLM.CATEGORY=CLMCTG.INTERNAL_VALUE"
				+ "  LEFT OUTER JOIN AV.CLAIMTYPES  CLMTYP" + "      ON CLM.CLAIMTYPE=CLMTYP.INTERNAL_VALUE"
				+ " LEFT OUTER JOIN AV.INSUREDINDICATOR INSIND" + "    ON CLMPOL.INSURED_INDICATOR=INSIND.INTERNAL_VALUE"
				+ "      LEFT OUTER JOIN AV.GROUPINDICATOR  GRPIND"
				+ "                   ON CLMPOL.MAJOR_LOB_AV = GRPIND.INTERNAL_VALUE"
				+ "   LEFT OUTER JOIN AV.REPORTINGPRODUCTTYPE  RPTPRDTYP"
				+ "                ON CLMPOL.POLICY_REPORTING_PRODUCT_TYPE_AV = RPTPRDTYP.INTERNAL_VALUE"
				+ "   LEFT OUTER JOIN AV.POLICYPRODUCTSUBTYPE  PRDSUBTYP "
				+ "               ON CLMPOL.PRODUCT_SUB_TYPE_AV  = PRDSUBTYP.INTERNAL_VALUE "
				+ "LEFT OUTER JOIN (SELECT VALHIS.CLAIMPOLICYID,SUM(VALHIS.GROSSAMOUNT) AS GROSS,"
				+ "SUM(VALHIS.NETAMOUNT) AS NET," + "SUM(VALHIS.REMBALANCE) AS REM "
				+ "FROM CLAIMS.VALUATIONHISTORY VALHIS " + "WHERE VALHIS.ENDDATE IS NULL "
				+ "AND VALHIS.CLAIMPOLICYSTATUS != 11 "
				+ "AND VALHIS.CLAIMCOVERAGESTATUS != 11 GROUP BY  VALHIS.CLAIMPOLICYID) AS POLAM ON  POLAM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID "
				+ " WHERE (LPOL.UPDATED_WHEN=(SELECT MAX(UPDATED_WHEN) FROM POLICY.LIFEPOLICY B WHERE LPOL.HOSTCONTRACTID=B.HOSTCONTRACTID))"
				+ "   AND CLMCOV.COVERAGETYPE ='01' AND CLMPOL.REPORTING_STATUS IN ";	
	
public static final String ClaimFinancialAtPayeeLevelQuery = "SELECT PROCSITES.DESCR AS POLICY_SITE, "+
"REGION.DESCR AS REGION, PARTY.CLIENT_TYPE_ID,PARTY.SEARCH_COMPANY_NAME,PARTY.SEARCH_LAST_NAME,"+
"CLMPOL.CONTESTABLE AS PolFlagCONTESTABLE, "+
"CLMPOL.COMPROMISED AS PolFlagCOMPROMISED, "+
"CLMPOL.UNDERLEGALREVIEW AS PolFlagUNDERLEGALREVIEW, "+
"CLMPOL.PAIDTOINTERPLEADER AS PolFlagPAIDTOINTERPLEADER, "+
"CLMPOL.COMMONDISASTERCLAUSE AS PolFlagCOMMONDISASTERCLAUSE, "+
"CLMPOL.BPO_UNDERINVESTIGATION AS PolFlagBPO_UNDERINVESTIGATION, "+
"CLMPOL.BPO_CLAIMDEFERRED AS PolFlagBPO_CLAIMDEFERRED, "+
"CLMPOL.BPO_VIATICALCLAIM AS PolFlagBPO_VIATICALCLAIM, "+
"CLMPOL.BPO_CLIENTREVIEWREQUIRED AS PolFlagBPO_CLIENTREVIEWREQUIRED, "+
"CLM.CONTESTABLE AS ClmFlagCONTESTABLE, "+
"CLM.COMPROMISED AS ClmFlagCOMPROMISED, "+
"CLM.UNDERLEGALREVIEW AS ClmFlagUNDERLEGALREVIEW, "+
"CLM.PAIDTOINTERPLEADER AS ClmFlagPAIDTOINTERPLEADER, "+
"CLM.COMMONDISASTERCLAUSE AS ClmFlagCOMMONDISASTERCLAUSE, "+
"CLM.BPO_UNDERINVESTIGATION AS ClmFlagBPO_UNDERINVESTIGATION, "+
"CLM.BPO_CLAIMDEFERRED AS ClmFlagBPO_CLAIMDEFERRED, "+
"CLM.BPO_VIATICALCLAIM AS ClmFlagBPO_VIATICALCLAIM, "+
"CLM.BPO_CLIENTREVIEWREQUIRED AS ClmFlagBPO_CLIENTREVIEWREQUIRED, "+
"PROCSITES.DESCR AS POLICY_SITE, "+
		 	"LEFT(COMPCODE.DESCR,3) AS COMPANY, "+  
		 	"CLMPOL.POLICYNUMBER AS POLICY, "+
		  "CLM.CLAIMNUMBER AS CLAIM, "+ 
		  "PARTY.SEARCH_FIRST_NAME AS INSFIRST, "+
"PARTY.BPO_SEARCH_MIDDLE_NAME AS INSMIDDLE, "+
"CLMTYP.DESCR AS CLAIMTYPE, "+
"INSIND.DESCR AS INSIND, "+
"GRPIND.DESCR AS MAJORLOB, "+
"(SELECT RES_ST.DESCR FROM AV.STATE RES_ST,CLIENT.CLIENT_ADDRESS CADD,CLIENT.ADDRESS AD WHERE RES_ST.INTERNAL_VALUE = AD.STATE AND CADD.ADDRESS_ID = AD.ADDRESS_ID AND AD.ADDRESS_TYPE_ID IN(1,0) AND CADD.CLIENT_ID = PARTY.CLIENT_ID ORDER BY AD.UPDATED_WHEN DESC FETCH FIRST 1 ROW ONLY) "+
"AS INSRESST, "+
"CLMCTG.DESCR AS SPLHANDLECODE, "+
"MANLOSS.DESCR AS MANNER, "+
"COFDEATH.DESCR AS CAUSEOFDEATH, "+
"CLM.NOTIFYRCPTDATE AS NOTIFIEDDATE, "+
"CLM.OCCURRENCEDATE AS DATEOFLOSS, "+
"CLMPOL.ISSUEDATE AS ISSUEDATE, "+
"STATE.DESCR AS ISSUESTATE, "+
"CLM.CLAIM_CLOSE_DATE AS CLOSEDDATE, "+
"CLMMGMSTS.DESCR AS CLAIMSTATUS, "+
"CLM.EXAMINER AS EXAMINER, "+
"CLMPOL.DATE_REPORTED AS DATEPOLICYREPORTED, "+
"CLMPOL.POLICY_DATE_ENTERED AS DATEPOLICYENTERED, "+
"CLMPOL.CYBERPAIDDATE AS CYBERPAIDDATE, "+
"POLRPTSTS.DESCR AS POLRPTNGSTATUS, "+
"POLSTS.DESCR AS POLICYSTATUS, "+
"POLCOVCLMSTS.DESCR AS POLICYMANAGEMENTSTATUS, "+
"POLPRDCDE.DESCR AS PRODUCTTYPE, "+
"RPTPRDTYP.DESCR AS REPORTINGPRODUCTTYPE, "+
"PRDSUBTYP.DESCR AS PRODUCTSUBTYPE, "+
"CLMCOV.PLANCODE AS PLANCODE, "+
"PARTTYPE.DESCR AS PARTYPE, "+
"BEGIND.DESCR AS BEAGLEIND, "+
"CASE "+
	"CLMPOL.PAY_ADJ_INDICATOR "+
	"WHEN 0 THEN 'Unknown' "+
	"WHEN 1 THEN 'Yes' "+
	"WHEN 2 THEN 'No' "+
"END PAYADJ, "+
"CLMCOV.BENEFITAMOUNT AS csAFACEAMT, "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) AS cmADC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.TYPE IN(11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT = 0 AND CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) - "+
 "(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) AS cmADC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.TYPE IN(11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT = 1 AND CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) "+
"AS cmAFACEAMT, "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) AS ADBDC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.TYPE = 84 AND CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.DEBITCREDIT = 0 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) AS ADBDC0 FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.TYPE = 84 AND CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.DEBITCREDIT = 1 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) "+
"AS ADBBENAMT, "+
 "(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.DEBITCREDIT = 0 AND TYPE = 12 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM WHERE CLMAMTITM.LEVEL IN(1,2) AND CLMAMTITM.DEBITCREDIT = 1 AND TYPE = 12 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) "+
"AS PUAAMOUNT, "+
"POLAM.GROSS AS POLGROSSAMOUNT, "+
"POLAM.NET AS POLNETAMT, "+
"POLAM.REM AS POLREMAININGBAL, "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMPOL.CLAIMPOLICYID = CLMAMTITM.CLAIMPOLICYID AND CLMAMTITM.TYPE IN (11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6)- "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMPOL.CLAIMPOLICYID = CLMAMTITM.CLAIMPOLICYID AND CLMAMTITM.TYPE IN (11,12,64,65,66,84) AND CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6) "+
"AS cmAFACEAMTPAID, "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT = 0 AND CLMAMTITM.TYPE = 84 AND CLMAMTITM.LEVEL = 3 AND STTLMNT.STATUS = 6 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT = 1 AND CLMAMTITM.TYPE = 84 AND CLMAMTITM.LEVEL = 3 AND STTLMNT.STATUS = 6 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) "+
"AS ADBBENAMTPAID, "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT = 0 AND CLMAMTITM.TYPE = 12 AND CLMAMTITM.LEVEL = 3 AND STTLMNT.STATUS = 6 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM( CLMAMTITM.AMOUNT ),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT = 1 AND CLMAMTITM.TYPE = 12 AND CLMAMTITM.LEVEL = 3 AND STTLMNT.STATUS = 6 AND CLMAMTITM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID) "+
"AS PUAAMTPAID, "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.TYPE IN (2, 4, 14) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.TYPE IN (2, 4, 14) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) "+
"AS PREMADJUSTPAID, "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.TYPE IN (13,26) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.TYPE IN (13,26) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) "+
"AS DIVIDENDSPAID, "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.TYPE IN (15,86) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.TYPE IN (15,86) AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) "+
"AS LOANWITHHELD, "+
"(SELECT COALESCE(SUM(CLMINTITM.AMOUNT),0) FROM CLAIMS.INTERESTPROCEEDSITEM CLMINTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMINTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE STTLMNT.STATUS=6 AND CLMINTITM.IOPSTATUSCODE=0  AND CLMINTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)+ "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=0 AND CLMAMTITM.TYPE = 87 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID)- "+
"(SELECT COALESCE(SUM(CLMAMTITM.AMOUNT),0) FROM CLAIMS.CLAIMAMOUNTITEM CLMAMTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMAMTITM.SETTLEMENTID=STTLMNT.SETTLEMENTID WHERE CLMAMTITM.DEBITCREDIT=1 AND CLMAMTITM.TYPE = 87 AND CLMAMTITM.LEVEL=3 AND STTLMNT.STATUS=6 AND CLMAMTITM.CLAIMPOLICYID=CLMPOL.CLAIMPOLICYID) "+
"AS INTERESTPAID, "+
"PAYMNT.PAYEELASTNAME AS PAYEELASTNAME, "+
"PAYMNT.PAYEEFIRSTNAME AS PAYEEFIRSTNAME, "+
"PAYMNT.PAYEEMIDDLENAME AS PAYEEMIDNAME, "+
"PAYMNT.CORPNAME AS PAYEEORGNAME, "+
"(SELECT RES_ST.DESCR FROM AV.STATE RES_ST WHERE RES_ST.INTERNAL_VALUE = PAYMNT.RESADDRESSSTATE) "+
"AS BENRESSTATE, "+
"PAYTYPE.DESCR AS PAYMENTTYPE, "+
"PAYMNT.NETBENEFITPAYMENT AS NETPAYMENTAMT, "+
"PAYMNT.DATEPAID AS DATEPAID, "+
"CLMPAYSTS.DESCR AS PAYMENTSTATUS, "+
"ADJREASON.DESCR AS ADJUSTMENTREASON, "+
"(SELECT PROOFDEATHDATE FROM CLAIMS.INTERESTPROCEEDSITEM CLMINTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMINTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMPOL.CLAIMPOLICYID = CLMINTITM.CLAIMPOLICYID AND CLM.CLAIMID = CLMINTITM.CLAIMID AND STTLMNT.STATUS=6 AND PROOFDEATHDATE IS NOT NULL ORDER BY IOPSTATUSCODE ASC, CALCULATIONID DESC FETCH FIRST ROW ONLY) "+
"AS PROOFDEATHDATE, "+
"(SELECT PROOFLOSSDATE FROM CLAIMS.INTERESTPROCEEDSITEM CLMINTITM INNER JOIN CLAIMS.SETTLEMENT STTLMNT ON CLMINTITM.SETTLEMENTID = STTLMNT.SETTLEMENTID WHERE CLMPOL.CLAIMPOLICYID = CLMINTITM.CLAIMPOLICYID AND CLM.CLAIMID = CLMINTITM.CLAIMID AND STTLMNT.STATUS=6 AND  PROOFLOSSDATE IS NOT NULL ORDER BY IOPSTATUSCODE ASC, CALCULATIONID DESC FETCH FIRST ROW ONLY) "+
"AS PROOFLOSSDATE "+
"FROM  "+
 "CLAIMS.CLAIM CLM  "+
"INNER JOIN CLAIMS.CLAIMPOLICY CLMPOL ON  "+
"CLMPOL.CLAIMID = CLM.CLAIMID  "+
"INNER JOIN POLICY.LIFEPOLICY LPOL ON  "+
"CLMPOL.HOSTCONTRACTID = LPOL.HOSTCONTRACTID  "+
"INNER JOIN CLAIMS.CLAIMCOVERAGE CLMCOV ON  "+
"CLMCOV.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID  "+
"LEFT OUTER JOIN CLIENT.PARTY PARTY ON  "+
"CLM.INSUREDID = PARTY.CLIENT_ID  "+
"INNER JOIN CLAIMS.SETTLEMENT STLMNT ON  "+
"CLM.CLAIMID = STLMNT.CLAIMID  "+
"INNER JOIN CLAIMS.DESIGNATION DESG ON  "+
"(  "+
	"CLM.CLAIMID = DESG.CLAIMID  "+
	"AND CLMPOL.CLAIMPOLICYID = DESG.CLAIMPOLICYID  "+
")  "+
"INNER JOIN CLAIMS.SETTLEMENTASSOCIATION STLMNTASSO ON "+ 
"(  "+
"	STLMNT.SETTLEMENTID = STLMNTASSO.SETTLEMENTID  "+
"	AND DESG.DESIGNATIONID = STLMNTASSO.DESIGNATIONID  "+
"	AND CLM.CLAIMID = STLMNTASSO.CLAIMID  "+
")  "+
"INNER JOIN CLAIMS.PAYMENTDEFINITION PAYMNTDEF ON  "+
"(  "+
"	CLM.CLAIMID = PAYMNTDEF.CLAIMID  "+
"	AND STLMNT.SETTLEMENTID = PAYMNTDEF.SETTLEMENTID  "+
")  "+
"INNER JOIN CLAIMS.PAYMENT PAYMNT ON  "+
"(  "+
"	CLM.CLAIMID = PAYMNT.CLAIMID  "+
"	AND PAYMNTDEF.PAYMENTDEFINITIONID = PAYMNT.PAYMENTDEFINITIONID  "+
")  "+
"LEFT OUTER JOIN AV.BEAGLEIND BEGIND ON  "+
"CLMPOL.BEAGLE_IND = CAST(  "+
	"BEGIND.INTERNAL_VALUE AS CHAR( 10 )  "+
")  "+
"LEFT OUTER JOIN AV.CLAIMCATEGORY CLMCTG ON  "+
"CLM.CATEGORY = CLMCTG.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.CLAIMTYPES CLMTYP ON  "+
"CLM.CLAIMTYPE = CLMTYP.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.INSUREDINDICATOR INSIND ON  "+
"CLMPOL.INSURED_INDICATOR = INSIND.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.PARTICIPATIONTYPE PARTTYPE ON  "+
"CLMCOV.PARTICIPATION_CODE_ID = PARTTYPE.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.POLICYCOVERAGECLAIMSTATUS POLCOVCLMSTS ON  "+
"CLMPOL.POLCVRGCLAIMSTATUS = POLCOVCLMSTS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.POLICYPRODUCTCODE POLPRDCDE ON  "+
"CLMPOL.PRODUCTCODE = POLPRDCDE.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.POLICYREPORTINGSTATUS POLRPTSTS ON  "+
"CLMPOL.REPORTING_STATUS = POLRPTSTS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.POLICYSTATUS POLSTS ON  "+
"CLMPOL.POLICYSTATUS = POLSTS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.PROCESSINGSITES PROCSITES ON  "+
"CLMPOL.POLICY_SITE = PROCSITES.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.REGION REGION ON  "+
"LPOL.BPO_REGIONID = REGION.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.CAUSEOFDEATH COFDEATH ON  "+
"CLM.CLAIMCAUSE = COFDEATH.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.MANNEROFLOSS MANLOSS ON  "+
"CLM.MANNEROFOCCURRENCE = MANLOSS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.CLAIMMANAGEMENTSTATUS CLMMGMSTS ON  "+
"CLM.CLAIMMGMTSTATUS = CLMMGMSTS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.STATE STATE ON  "+
"CLMPOL.ISSUESTATE = STATE.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.CLAIMPAYMENTSTATUS CLMPAYSTS ON  "+
"PAYMNT.CLAIMPAYMENTSTATUS = CLMPAYSTS.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.CLAIMPAYMENTTYPES PAYTYPE ON  "+
"PAYMNT.PAYMENTTYPECODE = PAYTYPE.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.COMPANYCODE COMPCODE ON  "+
"LPOL.CARRIERCODE = CAST(  "+
"	COMPCODE.INTERNAL_VALUE AS CHAR( 10 )  "+
")  "+
"LEFT OUTER JOIN AV.ADJUSTMENTREASON ADJREASON ON  "+
"PAYMNT.ADJUSTMENTREASON = ADJREASON.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.GROUPINDICATOR GRPIND ON  "+
"CLMPOL.MAJOR_LOB_AV = GRPIND.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.REPORTINGPRODUCTTYPE RPTPRDTYP ON  "+
"CLMPOL.POLICY_REPORTING_PRODUCT_TYPE_AV = RPTPRDTYP.INTERNAL_VALUE  "+
"LEFT OUTER JOIN AV.POLICYPRODUCTSUBTYPE PRDSUBTYP ON  "+
"CLMPOL.PRODUCT_SUB_TYPE_AV = PRDSUBTYP.INTERNAL_VALUE  "+
"LEFT OUTER JOIN(  "+
	"SELECT  "+
	"	VALHIS.CLAIMPOLICYID,  "+
	"	SUM( VALHIS.GROSSAMOUNT ) AS GROSS,  "+
	"	SUM( VALHIS.NETAMOUNT ) AS NET,  "+
	"	SUM( VALHIS.REMBALANCE ) AS REM  "+
	"FROM  "+
"				CLAIMS.VALUATIONHISTORY VALHIS  "+
"	WHERE  "+
"		VALHIS.ENDDATE IS NULL  "+
"		AND VALHIS.CLAIMPOLICYSTATUS != 11  "+
"		AND VALHIS.CLAIMCOVERAGESTATUS != 11  "+
"	GROUP BY  "+
"		VALHIS.CLAIMPOLICYID  "+
") AS POLAM ON  "+
"POLAM.CLAIMPOLICYID = CLMPOL.CLAIMPOLICYID  "+
"WHERE  "+
"(  "+
"	LPOL.UPDATED_WHEN =(  "+
"		SELECT  "+
"			MAX( UPDATED_WHEN )  "+
"		FROM  "+
"			POLICY.LIFEPOLICY B "+ 
"		WHERE  "+
"			LPOL.HOSTCONTRACTID = B.HOSTCONTRACTID "+ 
"	)  "+
")  "+
"AND CLMCOV.COVERAGETYPE = '01'  "+
"AND PAYMNT.CLAIMPAYMENTSTATUS != 9 "+
			"AND CLMPOL.REPORTING_STATUS IN  ";


public static final String ClaimFinancialAtPayeeQuery = "SELECT DISTINCT claim.claimid, claim.CLAIMNUMBER, COD.DESCR AS causeOfDeath,"
        + "claim.INSUREDID, CLMPOL.DATE_REPORTED,clmcov.BENEFITAMOUNT,lifepolicy.PLANCODE,claimpolicy.POLICYNUMBER,claim.NOTIFYRCPTDATE AS notifyDate,claim.OCCURRENCEDATE,claim.PROCESSING_SITE,claim.PROOFLOSSDATE,claim.PROOFDEATHDATE, claim.NOTIFYENTRYDATE, claim.CLAIM_CLOSE_DATE, claim.OCCURRENCEDATE, "
        + "claimpolicy.POLCVRGCLAIMSTATUS, claim.CLAIMSTATUS, claim.ClaimType,COD.DESCR AS causeOfDeath,CLMMGMSTS.DESCR AS claimStaus FROM CLAIMS.CLAIMPOLICY AS claimpolicy LEFT JOIN CLAIMS.CLAIM AS claim ON claim.CLAIMID = "
        + "claimpolicy.CLAIMID LEFT JOIN POLICY.LIFEPOLICY AS lifepolicy ON lifepolicy.HOSTCONTRACTID = claimpolicy.HOSTCONTRACTID "
        +"LEFT JOIN AV.CAUSEOFDEATH COD ON "
	    +"COD.INTERNAL_VALUE = claim.CLAIMCAUSE " 
        +"LEFT OUTER JOIN AV.CLAIMMANAGEMENTSTATUS CLMMGMSTS ON"
	    +"claim.CLAIMMGMTSTATUS = CLMMGMSTS.INTERNAL_VALUE"
	    +"LEFT JOIN CLAIMS.CLAIMCOVERAGE CLMCOV ON"
		+"CLMCOV.CLAIMPOLICYID = claimpolicy.CLAIMPOLICYID"
	+"LEFT JOIN CLAIMS.CLAIMPOLICY CLMPOL ON"
		+"CLMPOL.CLAIMID = Claim.CLAIMID"
       + "WHERE  claim.NOTIFYENTRYDATE BETWEEN '2018-01-01' AND '2019-01-01' FETCH FIRST 30 ROWS ONLY";

}